Face: If no unistd.h, compile the default constructor with exception
operantnetworks/ndn-ind pull request #44
Opened 2021-06-02 10:58 UTC by jefft0

The default Face constructor is for connecting to the local NFD using Unix sockets. Windows and other systems without unistd.h can't do this. In this case, the library simply doesn't compile the default Face constructor. If an example has this as an option, then the example will have a linker failure. This pull request changes this case to compile the default Face constructor, but to throw an exception. Therefore, the examples will compile and link.

2021-06-02 13:38 UTC, maysax approved these changes

2021-06-02 21:06 UTC, yoursunny requested changes
It makes no sense to compile a program that always fails.
The default constructor should instead attempt to connect to the local forwarder (e.g. YaNFD) via TCP.

2021-06-03 15:49 UTC, KLIU-opnt approved these changes

2021-06-03 16:01 UTC, jefft0 commented
> The default constructor should instead attempt to connect to the local forwarder (e.g. YaNFD) via TCP.

This use case happens on Windows where there is no forwarder.

2021-06-03 16:01 UTC, merged